---
title: "SparXCC PAG 2025"
output: html_notebook
---

Importing SparXCC library:

```{r}
library(devtools)
#install_github("IbTJensen/CompoCor")
library(CompoCor)
```

Importing the tables:

```{r}
# Day samples
wallace_otu_counts_filtered_day <- read.csv("C:/Users/renat/Downloads/tmp/pag25/filtered_otu_table_day_filtered_rel_abund_cv_filtered.tsv", sep="\t", header=TRUE, row.names=1)
dim(wallace_otu_counts_filtered_day)
head(wallace_otu_counts_filtered_day)
colnames(wallace_otu_counts_filtered_day) <- gsub("^X", "", colnames(wallace_otu_counts_filtered_day))

# Night samples
wallace_otu_counts_filtered_night <- read.csv("C:/Users/renat/Downloads/tmp/pag25/filtered_otu_table_night_filtered_rel_abund_cv_filtered.tsv", sep="\t", header=TRUE, row.names=1)
dim(wallace_otu_counts_filtered_night)
head(wallace_otu_counts_filtered_night)
colnames(wallace_otu_counts_filtered_night) <- gsub("^X", "", colnames(wallace_otu_counts_filtered_night))

kremling_expression_counts_filtered <- read.csv("C:/Users/renat/Downloads/tmp/pag25/expression_counts_day_night_filtered_cv_filtered.tsv", sep="\t", header=TRUE, row.names=1)
head(kremling_expression_counts_filtered)

kremling_expression_counts_filtered_day <- kremling_expression_counts_filtered[, grep("day", names(kremling_expression_counts_filtered), value = TRUE)]
kremling_expression_counts_filtered_night <- kremling_expression_counts_filtered[, grep("night", names(kremling_expression_counts_filtered), value = TRUE)]

head(kremling_expression_counts_filtered_day)
dim(kremling_expression_counts_filtered_day)
colnames(kremling_expression_counts_filtered_day) <- gsub("day_", "", colnames(kremling_expression_counts_filtered_day))
head(kremling_expression_counts_filtered_day)

head(kremling_expression_counts_filtered_night)
dim(kremling_expression_counts_filtered_night)
colnames(kremling_expression_counts_filtered_night) <- gsub("night_", "", colnames(kremling_expression_counts_filtered_night))
head(kremling_expression_counts_filtered_night)

wallace_otu_counts_filtered_day_sorted <- wallace_otu_counts_filtered_day[ , colnames(kremling_expression_counts_filtered_day)]
wallace_otu_counts_filtered_night_sorted <- wallace_otu_counts_filtered_night[ , colnames(kremling_expression_counts_filtered_night)]
```

Transposing dataframes:

```{r}
wallace_otu_counts_filtered_day_transposed <- t(wallace_otu_counts_filtered_day_sorted)
wallace_otu_counts_filtered_night_transposed <- t(wallace_otu_counts_filtered_night_sorted)
kremling_expression_counts_filtered_day_transposed <- t(kremling_expression_counts_filtered_day)
kremling_expression_counts_filtered_night_transposed <- t(kremling_expression_counts_filtered_night)
```

Making sure row names (samples) are identical between OTU and Expression data:

```{r}
identical(row.names(wallace_otu_counts_filtered_day_transposed), row.names(kremling_expression_counts_filtered_day_transposed))
identical(row.names(wallace_otu_counts_filtered_night_transposed), row.names(kremling_expression_counts_filtered_night_transposed))
```

```{r}
SparXCC_output_day <- SparXCC_base(wallace_otu_counts_filtered_day_transposed,
                        kremling_expression_counts_filtered_day_transposed,
                        pseudo_count = 1,
                        var_min = 1e-05,
                        Find_m = TRUE,
                        B_m = 100,
			cores = 1)

write.table(SparXCC_output_day, file = "SparXCC_output_day_pag25.txt", sep = "\t")

SparXCC_output_night <- SparXCC_base(wallace_otu_counts_filtered_night_transposed,
                        kremling_expression_counts_filtered_night_transposed,
                        pseudo_count = 1,
                        var_min = 1e-05,
                        Find_m = TRUE,
                        B_m = 100,
			cores = 1)

write.table(SparXCC_output_night, file = "SparXCC_output_night_pag25.txt", sep = "\t")
```

